project:
  type: website
  output-dir: docs

website:
  title: "Spezialisierungspraktikum RNA Biology"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_processing_galaxy.qmd
        text: Processing
      - sidebar:Splicing
      
      - about.qmd
      
      
  sidebar:
    - id: Splicing
      title: "Splicing"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
      - href: voila_gui.qmd
        text: Visualisation
      - href: global_splicing.qmd
        text: Global analysis
      - href: tasks.qmd
        text: Tasks
      
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    toc-depth: 2



